### PR TITLE
PR: Some readme changes (https and flake8 link)

### PR DESCRIPTION
**Pull request by rlaverde**
Fixes: #24 
Fixes: #25

### CODE REVIEW

**Comment by goanpeca** [comment]
@rlaverde please refer to the issues on the description

**Comment by rlaverde** [comment]
> please refer to the issues on the description

done :smile:

**Comment by goanpeca** [comment]
Ready for merge?

**Comment by rlaverde** [comment]
> Ready for merge?

yes

**Comment by goanpeca** [comment]
Thanks :-)

**Pull request merged**
